name: purescript-docker

on:
  push:
    paths-ignore:
    - 'old/**'
    - '**/*.md'
  pull_request:
    paths-ignore:
    - 'old/**'
    - '**/*.md'

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: docker-build
      run: |
        docker build -t fluid-webapp .
