name: v0.4.2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'v0.4.2'
    - name: test
      run: |
        yarn install
        yarn run bundle-tests
        yarn run tests
    - name: bundle
      run: |
        yarn run bundle-app /new/ index.html
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/app/
        destination_dir: 0.4.2/
