name: v0.4.2-docker

on:
  push:
    branches:
      - 'v0.4.2'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'v0.4.2'
    - name: docker-build
      run: |
        docker build -t fluid-webapp .
